export const MODAL_BODY_TYPES = {
  CONFIRMATION: 'CONFIRMATION',
  ADD_USER: 'ADD_USER',
  UPDATE_USER: 'UPDATE_USER',
};
export const CONFIRMATION_MODAL_CLOSE_TYPES = {
  DELETE_USER: 'DELETE_USER',
};
